
[workspace]
authors = ["Hans Fangohr <hans.fangohr@mpsd.mpg.de>"]
channels = ["conda-forge"]
name = "python"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
notebook = "jupyter-lab pandas-with-units.ipynb"

[dependencies]
python = ">=3.14.0,<3.15"
pandas = ">=2.3.3,<3"
jupyter = ">=1.1.1,<2"
pint = ">=0.25,<0.26"
pint-pandas = ">=0.7.1,<0.8"
